version: '3.7'

services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    cpus: 0.5
    mem_limit: 512m
    memswap_limit: 1g